services:
  db:
    image: postgres:17.6
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: todo_fastapi
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=todo_db
    depends_on:
      - db
    command: sh -c "python init_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data: